# Generated by Django 5.2 on 2025-04-16 15:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscription_time', models.DateTimeField(auto_now_add=True)),
                ('curse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='cursos.curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'curse')},
            },
        ),
    ]
