# Generated by Django 5.2 on 2025-04-16 18:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_inscripcion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='curse',
            new_name='curso',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='inscription_time',
            new_name='fecha_inscripcion',
        ),
        migrations.RenameField(
            model_name='inscripcion',
            old_name='user',
            new_name='usuario',
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('usuario', 'curso')},
        ),
    ]
